version: "3"

services:
  app:
    build: ./app
    environment:
      - URL_SERVER: http://server:4000
    ports:
      - "3000:3000"

  server:
    build: ./server
    environment:
      - URL_DB: mongodb://db:27017/granger
    depends_on:
      - db

  db:
    image: mongo
