version: "3"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      URL_SERVER: "http://server:4000"
    ports:
      - "3000:3000"
    depends_on:
      - URL_SERVER
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      URL_DB: "mongodb://db:27017/granger"
    ports:
      - "4000"
    depends_on:
      - db
    volumes:

  db:
    image: mongo
