version: "3"

services:
  app:
    image: granger_app
    ports:
      - "3000:3000"

  server:
    image: granger_server
    environment:
      URL_DB: "mongodb://db:27017/granger"
    depends_on:
      - db

  db:
    image: mongo
