export const SHOW_SESSION_MODAL = "SHOW_SESSION_MODAL";
export const SHOW_LOGOUT_MODAL = "SHOW_LOGOUT_MODAL";
export const SHOW_MENU_MOBILE = "SHOW_MENU_MOBILE";
export const SHOW_DROPDOWN_PROFILE = "SHOW_DROPDOWN_PROFILE";
